config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

   root to: "tasks#index"
   get "tasks/new", to: "tasks#new"
   get "tasks/:id", to: "tasks#show", as: "task"
   post "tasks", to: "tasks#create"
   get "tasks/:id/edit", to: "tasks#edit", as: "edit"
   patch "tasks/:id", to: "tasks#update"
   delete "tasks/:id", to: "tasks#destroy", as: "delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :find_task, only: [:show, :update, :destroy, :edit]

  def index 
    @tasks = Task.all
  end 

  def new 
    @task = Task.new
  end 

  def show 
  end 

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end 
  
  def edit 
  end 

  def update 
    @task.update(task_params)
    redirect_to task_path(@task)
  end 

  def destroy 
    @task.destroy
    redirect_to root_path
  end 

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %><br>
  <%= f.label "Mark as done" %> <br />
  <%= f.check_box :completed %> <br />
  <%= f.submit %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Task Manager</h1>

<ul>
<% @tasks.each do |task| %>
<li><%= link_to task.title, task_path(task) %>: <br>Still to do: <%=task.completed%> </li>
<% end %>
</ul>

<p><%= link_to "Add a new task", tasks_new_path  %>

app/views/tasks/new.html.erb
<h1> Create a Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<p>Still to do: <%= @task.completed %></p>

<p><%= link_to "Edit the task", edit_path  %><br>

<%= link_to 'Delete', task_path(@task), method: :delete, data: {confirm: 'Are you sure you want to delete?'} %>

<p><%= link_to "Back to tasks", root_path  %>